services:
  # This is our main Django application
  - type: web
    name: finsight-ai-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "gunicorn finsight_project.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: finsight-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9 

databases:
  - name: finsight-db
    plan: free